# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WsCli < Formula
  desc "Webhook Simulator CLI Tool"
  homepage "https://github.com/mmpsoftware/ws-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Darwin_x86_64.tar.gz"
      sha256 "e3dcc58b9dc1475a4d654dbfc0c6286b042ab711a4cd6a4b7489e8cfb2ae9367"

      def install
        bin.install "ws-cli"
      end
    end
    on_arm do
      url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Darwin_arm64.tar.gz"
      sha256 "040abffd0b85e32ba1cf930896be198ca90a826a784c82e9a5aced47a6eb9db6"

      def install
        bin.install "ws-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Linux_x86_64.tar.gz"
        sha256 "b1f07988d7d47b286dbf2dbee9901d94dcf3b1d4ca941c0870a543d2e4dbe80b"

        def install
          bin.install "ws-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Linux_arm64.tar.gz"
        sha256 "89949bc4767c59bf58a59d31c6ab2acc1332088d90e483d5b6627b4b76b20098"

        def install
          bin.install "ws-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/ws-cli --version"
  end
end
