# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WsCli < Formula
  desc "Webhook Simulator CLI Tool"
  homepage "https://github.com/mmpsoftware/ws-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Darwin_x86_64.tar.gz"
      sha256 "790cfc774113cccbc1f9cfcd9d76ad2ec1e1473248351866de6d8ea5c56dae24"

      def install
        bin.install "ws-cli"
      end
    end
    on_arm do
      url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Darwin_arm64.tar.gz"
      sha256 "0a6766f71ecaf1abbb8da5dc0d0b91810a024673aae381a45a914c7c9e3e4219"

      def install
        bin.install "ws-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Linux_x86_64.tar.gz"
        sha256 "db1d07d09b509d6e17b2031156c255d035752b2771ddf8391eac69d1464aa0f1"

        def install
          bin.install "ws-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mmpsoftware/homebrew-ws-cli/releases/download/v1.0.0/homebrew-ws-cli_Linux_arm64.tar.gz"
        sha256 "1d131c5f190033f4c1a4832c9b9e177abda2b9ad8bddf65c3895044a0587da18"

        def install
          bin.install "ws-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/ws-cli --version"
  end
end
